# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: books
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    # volumes:
    #   - ./apps/mongo:/data/db
    ports:
      - 27018:27017
